// Mocks generated by Mockito 5.4.6 from annotations
// in movies_explorer/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:flutter_bloc/flutter_bloc.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_explorer/features/favorites/data/repositories/favorite_repository.dart'
    as _i6;
import 'package:movies_explorer/features/favorites/presentation/bloc/favorite_bloc.dart'
    as _i16;
import 'package:movies_explorer/features/favorites/presentation/bloc/favorite_event.dart'
    as _i17;
import 'package:movies_explorer/features/favorites/presentation/bloc/favorite_state.dart'
    as _i7;
import 'package:movies_explorer/features/movie/data/repositories/movie_repository.dart'
    as _i2;
import 'package:movies_explorer/features/movie/presentation/bloc/movie_bloc.dart'
    as _i10;
import 'package:movies_explorer/features/movie/presentation/bloc/movie_event.dart'
    as _i12;
import 'package:movies_explorer/features/movie/presentation/bloc/movie_state.dart'
    as _i3;
import 'package:movies_explorer/features/moviedetails/presentation/bloc/movie_details_bloc.dart'
    as _i14;
import 'package:movies_explorer/features/moviedetails/presentation/bloc/movie_details_event.dart'
    as _i15;
import 'package:movies_explorer/features/moviedetails/presentation/bloc/movie_details_state.dart'
    as _i5;
import 'package:movies_explorer/features/moviedetails/repositories/movie_details_repository.dart'
    as _i4;
import 'package:movies_explorer/features/theme/bloc/theme_bloc.dart' as _i18;
import 'package:movies_explorer/features/theme/bloc/theme_event.dart' as _i19;
import 'package:movies_explorer/features/theme/bloc/theme_state.dart' as _i9;
import 'package:movies_explorer/features/theme/repository/theme_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieState_1 extends _i1.SmartFake implements _i3.MovieState {
  _FakeMovieState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailsRepository_2 extends _i1.SmartFake
    implements _i4.MovieDetailsRepository {
  _FakeMovieDetailsRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailsState_3 extends _i1.SmartFake
    implements _i5.MovieDetailsState {
  _FakeMovieDetailsState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoriteRepository_4 extends _i1.SmartFake
    implements _i6.FavoriteRepository {
  _FakeFavoriteRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoriteState_5 extends _i1.SmartFake implements _i7.FavoriteState {
  _FakeFavoriteState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThemeRepository_6 extends _i1.SmartFake
    implements _i8.ThemeRepository {
  _FakeThemeRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThemeState_7 extends _i1.SmartFake implements _i9.ThemeState {
  _FakeThemeState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieBloc extends _i1.Mock implements _i10.MovieBloc {
  MockMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository =>
      (super.noSuchMethod(
            Invocation.getter(#movieRepository),
            returnValue: _FakeMovieRepository_0(
              this,
              Invocation.getter(#movieRepository),
            ),
          )
          as _i2.MovieRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i3.MovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieState_1(this, Invocation.getter(#state)),
          )
          as _i3.MovieState);

  @override
  _i11.Stream<_i3.MovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i11.Stream<_i3.MovieState>.empty(),
          )
          as _i11.Stream<_i3.MovieState>);

  @override
  void add(_i12.MovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.MovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.MovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.MovieEvent>(
    _i13.EventHandler<E, _i3.MovieState>? handler, {
    _i13.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i13.Transition<_i12.MovieEvent, _i3.MovieState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i12.MovieEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onChange(_i13.Change<_i3.MovieState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieDetailsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailsBloc extends _i1.Mock implements _i14.MovieDetailsBloc {
  MockMovieDetailsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieDetailsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieDetailsRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.MovieDetailsRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.MovieDetailsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailsState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.MovieDetailsState);

  @override
  _i11.Stream<_i5.MovieDetailsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i11.Stream<_i5.MovieDetailsState>.empty(),
          )
          as _i11.Stream<_i5.MovieDetailsState>);

  @override
  void add(_i15.MovieDetailsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i15.MovieDetailsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.MovieDetailsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i15.MovieDetailsEvent>(
    _i13.EventHandler<E, _i5.MovieDetailsState>? handler, {
    _i13.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i13.Transition<_i15.MovieDetailsEvent, _i5.MovieDetailsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i15.MovieDetailsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onChange(_i13.Change<_i5.MovieDetailsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FavoriteBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteBloc extends _i1.Mock implements _i16.FavoriteBloc {
  MockFavoriteBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FavoriteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoriteRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.FavoriteRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.FavoriteState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeFavoriteState_5(this, Invocation.getter(#state)),
          )
          as _i7.FavoriteState);

  @override
  _i11.Stream<_i7.FavoriteState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i11.Stream<_i7.FavoriteState>.empty(),
          )
          as _i11.Stream<_i7.FavoriteState>);

  @override
  void add(_i17.FavoriteEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i17.FavoriteEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.FavoriteState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i17.FavoriteEvent>(
    _i13.EventHandler<E, _i7.FavoriteState>? handler, {
    _i13.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i13.Transition<_i17.FavoriteEvent, _i7.FavoriteState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i17.FavoriteEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onChange(_i13.Change<_i7.FavoriteState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeBloc extends _i1.Mock implements _i18.ThemeBloc {
  MockThemeBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ThemeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeThemeRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.ThemeRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.ThemeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeThemeState_7(this, Invocation.getter(#state)),
          )
          as _i9.ThemeState);

  @override
  _i11.Stream<_i9.ThemeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i11.Stream<_i9.ThemeState>.empty(),
          )
          as _i11.Stream<_i9.ThemeState>);

  @override
  void add(_i19.ThemeEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i19.ThemeEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.ThemeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i19.ThemeEvent>(
    _i13.EventHandler<E, _i9.ThemeState>? handler, {
    _i13.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i13.Transition<_i19.ThemeEvent, _i9.ThemeState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i19.ThemeEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onChange(_i13.Change<_i9.ThemeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
